### ISSUE TITLE
尝试修改Vue官方例子之Markdown编辑器

### ISSUE THREAD

**Issue by Pyloons** [Pyloons/pyloons.github.io#3]
这次修改的目标是将[官方给出的Markdown编辑器](https://cn.vuejs.org/v2/examples/)进行各模块的解耦，实现完全组件化。以下是部分代码：
1. 样式
```css
html, body, #editor {
  margin: 0;
  height: 100%;
  font-family: Arial, Helvetica, sans-serif;
  color: #333;
}

textarea, #editor div {
  display: inline-block;
  width: 49%;
  height: 100%;
  vertical-align: top;
  box-sizing: border-box;
  padding: 0 20px;
}

textarea {
  border: none;
  border-right: 1px solid #ccc;
  resize: none;
  outline: none;
  background-color: #f6f6f6;
  font-size: 14px;
  font-family: Courier New, Courier, monospace;
  padding: 20px;
}

code {
  color: #f66;
}
```
2. Html
```html
<div id="main">
  <markdown-editor></markdown-editor>
</div>
```
3. js
```javascript
      Vue.component('markdown-editor', {
        template:
        `
        <div id="editor">
          <input-box @raw-input="raw_input"></input-box>
          <output-box :outputs="pre_output"></output-box>
        </div>
        `,
        data: function() {
          return {
            pre_output: '<h1>hello</h1>',
          }
        },
        methods: {
          raw_input: function(data) {
            this.pre_output = data
            return this.pre_output
          },
        },
      });

      Vue.component('output-box', {
        template:'<div v-html="compiledMarkdown">{{compiledMarkdown}}</div>',
        props: ['outputs'],
        computed: {
          compiledMarkdown: function () {
            return marked(this.outputs);
          }
        },
      })

      Vue.component('input-box', {
        template:`
          <textarea :value="input" @input="update"></textarea>
        `,
        data: function() {
          return {
            input: '# hello',
          }
        },
        methods: {
          update: _.debounce(function(e) {
            this.input = e.target.value
            this.$emit('raw-input', this.input)
          }, 100)
        },
      })

      new Vue({
        el: '#main',
      })
```
勉强搭建起了功能，个中逻辑，不甚明了……希望在以后的学习生活中能够悟出其用法的规律……
